//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Arbitro.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Arbitro extends Pessoa {
	private String categoria;
}
