//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Clube.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Clube {
	private String nome;
	private int anoFundacao;
	private Estadio estadio;
	private ArrayList<Jogador> jogadores;
	private Tecnico tecnico;
}
