//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Estadio.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Estadio {
	private String nome;
	private String cidade;
}
