//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Jogador.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Jogador extends Pessoa {
	private String posicao;
	private bool capitao;
}
