//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Partida.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Partida {
	private date data;
	private string hora;
	private Estadio estadio;
	private Clube timeCasa;
	private Clube timeVisitante;
	private Arbitro arbitro;
}
