//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 10/11/2023
//  @ Author : 
//
//




public class Pessoa {
	protected String nome;
	protected String cpf;
	protected date dataNascimento;
	protected double peso;
	protected double QI;
	protected double altura;
	protected String nacionalidade;
	protected void habilidade() {
	
	}
}
